# NumPy Exercises - Solutions

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [13]:
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [14]:
array=np.ones(10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [19]:
array=np.array([5,5,5,5,5,5,5,5,5,5])
array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [23]:
array=np.array(range(10,51))
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [41]:
array =  np.arange(0, 9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [43]:
arrays=np.identity(3)
arrays

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [47]:
array=np.random.normal(0,1)
array

-0.2276998471384269

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [3]:
import numpy as np
array=np.random.normal(0,1,25)
array

array([-0.36280305,  1.07421958,  0.06850286,  0.26684832, -0.54492966,
       -0.23504116,  0.31615932, -0.44853901,  0.66403307,  0.93697773,
       -0.33519017, -0.15872094,  0.23730221, -0.56879834, -0.8724079 ,
       -0.08362068,  1.26834696,  0.2403547 ,  0.18139132,  0.3123161 ,
       -0.53110729,  0.8322065 ,  0.91622368, -0.71494618, -1.36331518])

#### Create the following matrix:

In [14]:
array=np.arange(1,101).reshape(10,10)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
array=np.linspace(0, 1, 20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [16]:
array=np.arange(1,26).reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [17]:
array[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [18]:
array[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [5]:
import numpy as np
array=np.arange(1,26).reshape(5,5)
array[1:4,1:2]

array([[ 7],
       [12],
       [17]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
array=np.arange(1,26).reshape(5,5)
array[4: ,0:]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
array[3: ,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [50]:
a=np.sum(array)
a

325

#### Get the standard deviation of the values in mat

In [51]:
sd = np.std(array)
sd

7.2111025509279782

#### Get the sum of all the columns in mat

In [53]:
sum_of_cols = np.sum(array, axis = 0)
sum_of_cols

array([55, 60, 65, 70, 75])

# Great Job!